name: Build Wasm Manual

on:
  workflow_dispatch:
    inputs:
      runtime:
        description: 'Runtime'
        required: true
        type: choice
        options:
        - alphanet
        - mainnet
        - chaosnet

env:
  CARGO_TERM_COLOR: always
  Runtime: ${{ github.event.inputs.runtime }}

jobs:
  format:
    runs-on: ubuntu-latest
    name: Build Wasm files
    steps:
    - name: Move wasm files
      run: |
        echo $Runtime
        echo "$Runtime"
        echo ${Runtime}