name: Run Benchmarks Manual

on:
  workflow_dispatch:
    inputs:
      runtime:
        description: 'Runtime'
        required: true
        type: choice
        options:
        - alphanet
        - mainnet
        - chaosnet

env:
  CARGO_TERM_COLOR: always
  Runtime: ${{ github.event.inputs.runtime }}

jobs:
  run-benchmarks:
    runs-on: ubuntu-latest
    name: Run Benchmarks
    steps:
    - uses: hecrj/setup-rust-action@v1
    - uses: actions/checkout@v3

    - name: Setup Rust toolchain
      run: rustup show

    - name: Build the Ternoa client
      run: cargo build --release --features runtime-benchmarks

    - name: Run benchmarks
      run: ./scripts/benchmarks/"$Runtime"/run_benchmarks.sh

    - name: Switch to a new branch
      run: git checkout -b github/benchmarks

    - uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions

    