name: Test WOrkflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags' 

env:
  CARGO_TERM_COLOR: always
  Runtime: ${{ github.event.inputs.runtime }}

jobs:
  format:
    runs-on: ubuntu-latest
    name: Test Job
    steps:
    - uses: hecrj/setup-rust-action@v1
    - uses: actions/checkout@v3

    - name: Echo world!
      run: echo Hello World!